# Generated by Django 4.1.7 on 2023-03-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30)),
                ('matric_number', models.CharField(editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hall', models.CharField(max_length=20)),
                ('room_number', models.CharField(default='A01', max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
