# Generated by Django 4.1.7 on 2023-03-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='matric_number',
        ),
        migrations.AddField(
            model_name='student',
            name='matric',
            field=models.CharField(default='23/0001', max_length=7, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
