# Generated by Django 4.1.3 on 2023-04-12 22:30

import django.contrib.auth.validators
from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=6
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.FileField(
                blank=True,
                max_length=150,
                null=True,
                upload_to=students.models.User.profilePicture,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="default@gmail.com",
                max_length=254,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="firstname",
            field=models.CharField(
                default="John", max_length=30, verbose_name="first_name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="lastname",
            field=models.CharField(
                default="Doe", max_length=30, verbose_name="last_name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="John_doe",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=30,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
