# Generated by Django 4.1.7 on 2023-03-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_matric_number_student_matric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room_number',
            field=models.CharField(max_length=4),
        ),
    ]
