# Generated by Django 4.2 on 2023-04-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254, unique=True, verbose_name='email'),
        ),
    ]
