# Generated by Django 4.1.7 on 2023-03-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
        ('students', '0003_alter_student_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='halls.hall'),
        ),
    ]
