# Generated by Django 4.1.7 on 2023-03-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='fname',
            field=models.CharField(default='John', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='lname',
            field=models.CharField(default='Doe', max_length=15),
            preserve_default=False,
        ),
    ]
