# Generated by Django 4.1.7 on 2023-03-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_name_student_fname_student_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='oname',
            field=models.CharField(default='Smith', max_length=15),
            preserve_default=False,
        ),
    ]
