# Generated by Django 4.1.7 on 2023-03-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_oname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='oname',
        ),
        migrations.AddField(
            model_name='student',
            name='othername',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
