# Generated by Django 4.1.3 on 2023-04-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="name",
            field=models.CharField(
                choices=[
                    ("bethel splendor", "bethel splendor"),
                    ("queen esther", "queen esther"),
                    ("nelson mandela", "nelson mandela"),
                    ("felicia adebisi", "felicia adebisi"),
                    ("havila", "havila"),
                    ("samuel akande", "samuel akande"),
                ],
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
