# Generated by Django 4.2 on 2023-04-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_alter_hall_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(choices=[('bethel splendor', 'bethel splendor'), ('queen esther', 'queen esther'), ('nelson mandela', 'nelson mandela'), ('felicia adebisi', 'felicia adebisi'), ('havila', 'havila'), ('samuel akande', 'samuel akande')], max_length=30, primary_key=True, serialize=False),
        ),
    ]
