# Generated by Django 4.2 on 2023-04-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halls", "0004_alter_hall_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="name",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
