# Generated by Django 4.2 on 2023-04-14 16:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complain_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('carpentry', 'carpentry'), ('pest', 'pest'), ('plumbing', 'plumbing'), ('electrical', 'electrical'), ('other', 'other')], max_length=15)),
                ('details', models.TextField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Pending', max_length=12)),
                ('review', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='students.student')),
            ],
        ),
    ]
