# Generated by Django 4.1.7 on 2023-03-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('category', models.CharField(max_length=15)),
                ('details', models.TextField(blank=True, null=True)),
                ('room_number', models.CharField(max_length=4)),
                ('student', models.CharField(max_length=50)),
                ('priority', models.CharField(editable=False, max_length=6)),
                ('status', models.CharField(default='Pending', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('matric_number', models.CharField(editable=False, max_length=7, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('hall', models.CharField(max_length=20)),
            ],
        ),
    ]
