# Generated by Django 4.1.7 on 2023-03-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='priority',
        ),
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.CharField(default='A01', max_length=4),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
