# Generated by Django 4.2 on 2023-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('carpentry', 'carpentry'), ('pest', 'pest'), ('plumbing', 'plumbing'), ('electrical', 'electrical'), ('other', 'other')], max_length=15),
        ),
    ]
