# Generated by Django 4.2 on 2023-04-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_rename_review_complaint_reviewfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='reviewfield',
            new_name='review',
        ),
    ]
