# Generated by Django 4.1.7 on 2023-03-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='student',
        ),
    ]
