# Generated by Django 4.1.7 on 2023-03-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_hall'),
        ('complaints', '0004_remove_complaint_date_remove_complaint_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='room_number',
        ),
        migrations.AddField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(default=0.01818181818181818, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='students.student'),
            preserve_default=False,
        ),
    ]
