# Generated by Django 4.1.7 on 2023-03-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_remove_complaint_room_number_complaint_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='student',
            new_name='student_id',
        ),
    ]
