# Generated by Django 4.1.7 on 2023-03-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
        ('complaints', '0010_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='hall',
            field=models.ForeignKey(default='Gideon Troopers', on_delete=django.db.models.deletion.CASCADE, to='halls.hall'),
            preserve_default=False,
        ),
    ]
