# Generated by Django 4.1.7 on 2023-03-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_complaint_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='hall',
        ),
    ]
