# Generated by Django 4.1.3 on 2023-04-12 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("halls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HallAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "hall",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="halladmins",
                        to="halls.hall",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
