# Generated by Django 4.1.7 on 2023-03-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
        ('halladmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halladmin',
            name='hall',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='halladmin', to='halls.hall'),
        ),
    ]
