# Generated by Django 4.2 on 2023-04-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halladmin", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="halladmin",
            name="staff_number",
            field=models.CharField(default=None, max_length=8, unique=True),
        ),
    ]
